[package]
name = "crate3"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]

[dependencies]
crate2 = { path = "../../crate2/crate2" }

[dev-dependencies]
crate2 = { path = "../../crate2/crate2", features = ["feature1"] }
